### PR TITLE
Switch to OVRO-LWA as the name for `lwa_antpos.station`.

### PR DESCRIPTION
**Pull request by caseyjlaw**
Before deploying this, we will need to update the CASA data (run `!update-data`) on Cal-Im servers.

### CODE REVIEW

**Review by jaycedowell — APPROVED** [review]
I wrote it so I would hope that I like it.

**Comment by caseyjlaw** [comment]
haha. I tried to undo that, but couldn't figure out how.

**Comment by caseyjlaw** [comment]
I've installed this to `development` and `deployment`. How can we test that MS files are valid?
I did run `!update-data` in CASA with root permissions, which updated the internal data (from what I can tell).

**Comment by jaycedowell** [comment]
I think CASA will complain if it doesn't recognize the observatory.  We could also try https://github.com/lwa-project/ovro_data_recorder/issues/28 again to see if that is fixed.

**Pull request merged**
